networks:
  wordlust:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: ${PROJECT}_nginx
    ports:
      - 9007:443
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - wordlust

  mysql:
    image: mysql:latest
    container_name: ${PROJECT}_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: wordlust
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - apnithali_db:/var/lib/mysql
    networks:
      - wordlust

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8087:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - wordlust


  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ${PROJECT}_php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - wordlust

  redis:
    image: redis:alpine
    container_name: ${PROJECT}_redis
    restart: unless-stopped
    ports:
      - 6377:6379
    networks:
      - wordlust

  composer:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ${PROJECT}_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html/${BRANCH}
    depends_on:
      - php
    user: laravel
    entrypoint: ['php', '/var/www/html/$BRANCH/composer']
    networks:
      - wordlust

  npm:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: ${PROJECT}_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html/${BRANCH}
    entrypoint: ['npm']
    user: node
    networks:
      - wordlust

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ${PROJECT}_artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html/${BRANCH}
    user: laravel
    entrypoint: ['php', '/var/www/html/$BRANCH/artisan']
    networks:
      - wordlust

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${PROJECT}_mailhog
    ports:
      - 1027:1025
      - 8027:8025
    networks:
      - wordlust

volumes:
  wordlust_db:
