networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: ${PROJECT}_nginx
    ports:
      - 9009:443
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: ${PROJECT}_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8089:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel


  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ${PROJECT}_php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: ${PROJECT}_redis
    restart: unless-stopped
    ports:
      - 6371:6379
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: ${PROJECT}_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html/${BRANCH}
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:latest
    container_name: ${PROJECT}_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html/${BRANCH}
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ${PROJECT}_artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html/${BRANCH}
    user: laravel
    entrypoint: ['php', '/var/www/html/${BRANCH}artisan']
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${PROJECT}_mailhog
    ports:
      - 1029:1025
      - 8029:8025
    networks:
      - laravel
