networks:
  mynetwork:
    name: ${NETWORK}

services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "${WEB_PORT:-80}:80"
      - "${WEBS_PORT:-443}:443"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailpit
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel}
      MYSQL_USER: ${MYSQL_USER:-laravel}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mynetwork

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "${PHP_PORT:-9000}:9000"
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - mynetwork

  composer:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    working_dir: /var/www/html/${BRANCH}
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - mynetwork

  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    user: ${UID}
    ports:
      - "${NPM_PORT_1:-3000}:3000"
      - "${NPM_PORT_2:-3001}:3001"
      - "${NPM_PORT_3:-5173}:5173"
    working_dir: /var/www/html/${BRANCH}
    entrypoint: [ 'npm' ]
    networks:
      - mynetwork

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - mynetwork

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - "${MAILPIT_PORT_1:-1089}:1025"
      - "${MAILPIT_PORT_2:-8089}:8025"
    networks:
      - mynetwork

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - mynetwork
